name: GHAction example

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  ci_step:
    name: Build, Test CVE, and Push Docker image (if no critical/high CVEs)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "comanderdc/temp"
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: comanderdc
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: |
            type=registry,ref=comanderdc/temp
          cache-to: |
            type=registry,ref=comanderdc/temp

      - name: Scan for CVEs
        uses: aquasecurity/trivy-action@v0.20.0  # Consider using a specific version for stability
        with:
          image: ${{ steps.build.outputs.name }}  # Use output from build step
          format: json
          fail-on-vuln: true  # Fail workflow if critical/high CVEs are found

      - name: Push Docker image (if no critical/high CVEs)
        if: ${{ !success() || steps.scan_for_cves.outputs.vulnerability_count == 0 }}
        uses: docker/push-action@v3
        with:
          tags: ${{ steps.meta.outputs.tags }}