name: GHAction example

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

env:
  DOCKERHUB_USERNAME: comanderdc
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  TRIVY_USERNAME: $COMANDERDC
  TRIVY_PASSWORD: ${{ secrets.TOKEN_GITHUB }}

jobs:
  ci_step:
    name: Build, tag and push Docker image to DockerHub
    runs-on: ubuntu-latest
      
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v4
      
      - 
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: comanderdc/temp
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: comanderdc
          password: ${{ env.DOCKERHUB_TOKEN }}

      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=comanderdc/temp:cache 
          cache-to: |
            type=registry,ref=comanderdc/temp:cache  
          tags: ${{ steps.meta.outputs.tags }}

      - 
        name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      - 
        name: Check if image has critical or high vulnerabilities
        if: steps.trivy.outputs.exit-code == 1
        run: |
          echo "Image has critical or high vulnerabilities. Aborting deployment."
          exit 1

      - 
        name: Push Docker image to DockerHub
        if: steps.trivy.outputs.exit-code == 0
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=comanderdc/temp:cache 
          cache-to: |
            type=registry,ref=comanderdc/temp:cache  
          tags: ${{ steps.meta.outputs.tags }}