name: GHAction example

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  ci_step:
    name: Build, Test CVE, and Push Docker image (if no critical/high CVEs)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "comanderdc/temp"
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: comanderdc
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: |
            type=registry,ref=comanderdc/temp
          cache-to: |
            type=registry,ref=comanderdc/temp
          tags: ${{ steps.meta.outputs.tags }}
          push: false

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.40.0/trivy_0.40.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.40.0_Linux-64bit.deb

      - name: Scan for CVEs
        id: trivy_scan
        run: trivy image --format json --output trivy.json --severity HIGH,CRITICAL comanderdc/temp:$(echo ${{ steps.meta.outputs.tags }} | awk -F',' '{print $1}')

      - name: Save scan results
        run: cat trivy.json

      - name: Check CVE Scan Results
        id: check_scan
        run: |
          if grep -q '"Severity":"HIGH"\|"Severity":"CRITICAL"' trivy.json; then
            echo "vulnerable=true" >> $GITHUB_ENV
          else
            echo "vulnerable=false" >> $GITHUB_ENV

      - name: Push Docker image (if no critical/high CVEs)
        if: env.vulnerable == 'false'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
